import type { Provider, PentestSession, StreamMessage, Finding, PreflightCheck } from '@/types';

export const mockProviders: Provider[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'anthropic',
    displayName: 'Anthropic',
    enabled: true,
    apiKey: 'sk-ant-****************************abcd',
    baseUrl: '',
    isDefault: true,
    healthStatus: 'healthy',
    models: [
      { id: 'opus-4', modelId: 'claude-opus-4', displayName: 'Claude Opus 4', contextWindow: 200000, enabled: true },
      { id: 'sonnet-4', modelId: 'claude-sonnet-4', displayName: 'Claude Sonnet 4', contextWindow: 200000, enabled: true },
      { id: 'haiku-3.5', modelId: 'claude-haiku-3.5', displayName: 'Claude Haiku 3.5', contextWindow: 200000, enabled: false },
    ],
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI',
    type: 'zhipu',
    displayName: 'Zhipu AI',
    enabled: true,
    apiKey: 'zhipu-****************************efgh',
    baseUrl: 'https://api.z.ai/api/anthropic',
    isDefault: false,
    healthStatus: 'healthy',
    models: [
      { id: 'glm-4.7', modelId: 'glm-4.7', displayName: 'GLM-4.7', contextWindow: 128000, enabled: true },
      { id: 'glm-4.6', modelId: 'glm-4.6', displayName: 'GLM-4.6', contextWindow: 128000, enabled: true },
      { id: 'glm-4.5', modelId: 'glm-4.5', displayName: 'GLM-4.5', contextWindow: 128000, enabled: false },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai',
    displayName: 'OpenAI',
    enabled: false,
    apiKey: '',
    baseUrl: '',
    isDefault: false,
    healthStatus: 'unknown',
    models: [
      { id: 'gpt-4o', modelId: 'gpt-4o', displayName: 'GPT-4o', contextWindow: 128000, enabled: true },
      { id: 'gpt-4-turbo', modelId: 'gpt-4-turbo', displayName: 'GPT-4 Turbo', contextWindow: 128000, enabled: false },
    ],
  },
  {
    id: 'custom',
    name: 'Custom',
    type: 'custom',
    displayName: 'Custom',
    enabled: false,
    apiKey: '',
    baseUrl: '',
    isDefault: false,
    healthStatus: 'unknown',
    models: [],
  },
];

export const mockFindings: Finding[] = [
  {
    id: 'f1',
    title: 'Open SSH Port with Weak Cipher Suites',
    severity: 'High',
    category: 'Network',
    description: 'Port 22 is open and accepts weak cipher suites including 3DES-CBC and RC4.',
    evidence: 'nmap -sV -sC target.com\nPORT   STATE SERVICE\n22/tcp open  ssh     OpenSSH 7.4',
    remediation: 'Disable weak cipher suites in sshd_config. Use only chacha20-poly1305 and aes256-gcm.',
    cvssScore: 7.5,
    phaseName: 'Scanning',
    createdAt: '2025-02-16T10:30:00Z',
  },
  {
    id: 'f2',
    title: 'Missing Security Headers',
    severity: 'Medium',
    category: 'Web',
    description: 'Several important security headers are missing: X-Frame-Options, Content-Security-Policy, X-Content-Type-Options.',
    evidence: 'HTTP/1.1 200 OK\nServer: nginx/1.18\n(no security headers found)',
    remediation: 'Add X-Frame-Options: DENY, Content-Security-Policy, X-Content-Type-Options: nosniff headers.',
    cvssScore: 5.3,
    phaseName: 'Vulnerability Assessment',
    createdAt: '2025-02-16T10:45:00Z',
  },
  {
    id: 'f3',
    title: 'TLS 1.0/1.1 Supported',
    severity: 'Medium',
    category: 'SSL/TLS',
    description: 'The server supports deprecated TLS versions 1.0 and 1.1.',
    evidence: 'sslscan target.com\nTLSv1.0   enabled\nTLSv1.1   enabled',
    remediation: 'Disable TLS 1.0 and 1.1. Only allow TLS 1.2 and 1.3.',
    cvssScore: 4.8,
    phaseName: 'Scanning',
    createdAt: '2025-02-16T10:35:00Z',
  },
  {
    id: 'f4',
    title: 'Exposed Admin Panel',
    severity: 'Critical',
    category: 'Web',
    description: 'Admin panel accessible at /admin without IP restriction.',
    evidence: 'gobuster dir -u https://target.com -w common.txt\n/admin (Status: 200)',
    remediation: 'Restrict admin panel access by IP whitelist or VPN only.',
    cvssScore: 9.1,
    phaseName: 'Vulnerability Assessment',
    createdAt: '2025-02-16T10:50:00Z',
  },
];

export const mockStreamMessages: StreamMessage[] = [
  {
    id: 'm1',
    type: 'thinking',
    content: 'Analyzing target example.com. Starting with passive reconnaissance to gather information about the domain, subdomains, and exposed services before active scanning.',
    timestamp: '2025-02-16T10:00:00Z',
    isCollapsed: true,
  },
  {
    id: 'm2',
    type: 'text',
    content: 'Starting reconnaissance phase for example.com. I will begin with DNS enumeration and subdomain discovery.',
    timestamp: '2025-02-16T10:00:05Z',
  },
  {
    id: 'm3',
    type: 'tool_use',
    content: 'Running subfinder for subdomain enumeration...',
    toolName: 'subfinder',
    toolParams: { domain: 'example.com', silent: 'true' },
    timestamp: '2025-02-16T10:00:10Z',
  },
  {
    id: 'm4',
    type: 'tool_result',
    content: 'Found 12 subdomains:\n- api.example.com\n- admin.example.com\n- mail.example.com\n- dev.example.com\n- staging.example.com\n- cdn.example.com\n- blog.example.com\n- docs.example.com\n- status.example.com\n- app.example.com\n- ws.example.com\n- auth.example.com',
    toolName: 'subfinder',
    timestamp: '2025-02-16T10:00:30Z',
  },
  {
    id: 'm5',
    type: 'text',
    content: 'Found 12 subdomains. Now scanning for open ports on the main domain and key subdomains.',
    timestamp: '2025-02-16T10:00:35Z',
  },
  {
    id: 'm6',
    type: 'tool_use',
    content: 'Running nmap port scan...',
    toolName: 'nmap_scan',
    toolParams: { host: 'example.com', ports: '1-10000', flags: '-sV -sC' },
    timestamp: '2025-02-16T10:00:40Z',
  },
  {
    id: 'm7',
    type: 'tool_result',
    content: 'PORT     STATE SERVICE     VERSION\n22/tcp   open  ssh         OpenSSH 7.4\n80/tcp   open  http        nginx 1.18.0\n443/tcp  open  ssl/https   nginx 1.18.0\n3306/tcp open  mysql       MySQL 5.7.38\n8080/tcp open  http-proxy  Squid 4.6',
    toolName: 'nmap_scan',
    timestamp: '2025-02-16T10:01:20Z',
  },
  {
    id: 'm8',
    type: 'finding',
    content: 'Critical finding detected: Exposed admin panel at /admin',
    finding: mockFindings[3],
    timestamp: '2025-02-16T10:01:25Z',
  },
  {
    id: 'm9',
    type: 'text',
    content: 'Identified 5 open ports. MySQL port 3306 is externally accessible which is a security concern. Moving to vulnerability assessment phase.',
    timestamp: '2025-02-16T10:01:30Z',
  },
];

export const mockPreflightChecks: PreflightCheck[] = [
  { id: 'dns', label: 'DNS Resolution', description: 'Verify target resolves', status: 'pending' },
  { id: 'http', label: 'HTTP/HTTPS Reachable', description: 'Check web accessibility', status: 'pending' },
  { id: 'mcp', label: 'MCP Server Available', description: 'Verify MCP connection', status: 'pending' },
  { id: 'tools', label: 'Tools Available', description: 'Check required tools', status: 'pending' },
  { id: 'rate', label: 'Rate Limit Test', description: 'Check for blocking', status: 'pending' },
  { id: 'waf', label: 'WAF Detection', description: 'Detect WAF presence', status: 'pending' },
];

export const mockSession: PentestSession = {
  id: 'session-001',
  target: 'example.com',
  phase: 'Vulnerability Assessment',
  startedAt: '2025-02-16T10:00:00Z',
  duration: 1847,
  messages: mockStreamMessages,
  findings: mockFindings,
  tokensUsed: 45230,
  toolsUsed: 8,
};
